### ISSUE TITLE
Guided Contract Deployer : TypeError on click Set Pricing Range with invalid fields

### ISSUE THREAD

**Issue by pelsasser** [MarketProject/Dapp#40]
![image](https://user-images.githubusercontent.com/15096737/36179388-5030577c-10d9-11e8-8a50-c8b5684bf507.png)

If you got to the new Guided Contract Deployer, and click Set Pricing Range without entering valid fields, an error occurs.

@perfectmak any chance you can take a look?

**Comment by perfectmak** [comment]
Hmm... It looks like a web3 undefined error. That didn't happen before, I'll take a look.

**Comment by pelsasser** [comment]
Got it - probably from some of the recent merges.  I think @eswarasai tried to warn me about this - sorry

**Comment by pelsasser** [comment]
@perfectmak - it looks like this only happens in an incognito window.  Just tested in a normal chrome window, and the error doesn't happen

**Comment by perfectmak** [comment]
Hmmm... So is there a way we can fix this for incognito? Because Ideally the check:
`if (!web3) callback()` should prevent the undefined error.

**Comment by pelsasser** [comment]
I dont understand why it isn't preventing it to be honest.
