### ISSUE TITLE
Contract Explorer Page - BASE_TOKEN to show name and symbol

### ISSUE THREAD

**Issue by pelsasser** [MarketProject/Dapp#9]
Currently the contract explorer just reports the address of the `BASE_TOKEN` this can be improved by attempting to grab `name` and `symbol` fields from the addresses to display to users.  

Sorting and filtering on these fields would allow users to see all contracts tradeable with a specific base token.

**Comment by cryptomental** [comment]
Yesterday I came up with an idea how this could be implemented. I will try to finish today and open a pull request.

**Comment by cryptomental** [comment]
Pull request is ready for the review.

**Comment by eswarasai** [comment]
@pelsasser -- This is good to go for payout

**Comment by pelsasser** [comment]
@cryptomental and @eswarasai thanks guys - really appreciate all the help! @cryptomental - will get you some more ETH ;)
